# CMake generated Testfile for 
# Source directory: C:/Users/sakib/llama.cpp/tests
# Build directory: C:/Users/sakib/llama.cpp/build-android/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-tokenizer-0-bert-bge "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-bert-bge.gguf")
set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;114;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-command-r "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-command-r.gguf")
set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;115;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-deepseek-coder "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-deepseek-coder.gguf")
set_tests_properties(test-tokenizer-0-deepseek-coder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;116;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-deepseek-llm "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-deepseek-llm.gguf")
set_tests_properties(test-tokenizer-0-deepseek-llm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;117;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-falcon "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-falcon.gguf")
set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;118;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-gpt-2 "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-gpt-2.gguf")
set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;119;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-bpe "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-llama-bpe.gguf")
set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;120;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-spm "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;121;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-mpt "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-mpt.gguf")
set_tests_properties(test-tokenizer-0-mpt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;122;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-phi-3 "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-phi-3.gguf")
set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;123;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-qwen2 "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-qwen2.gguf")
set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;124;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-refact "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-refact.gguf")
set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;125;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-starcoder "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-0" "C:/Users/sakib/llama.cpp/models/ggml-vocab-starcoder.gguf")
set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;126;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizers-ggml-vocabs "C:/Users/sakib/llama.cpp/tests/test-tokenizers-repo.sh" "https://huggingface.co/ggml-org/vocabs" "C:/Users/sakib/llama.cpp/models/ggml-vocabs")
set_tests_properties(test-tokenizers-ggml-vocabs PROPERTIES  LABELS "main" WORKING_DIRECTORY "C:/Users/sakib/llama.cpp/build-android/bin" _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;64;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;129;llama_test_cmd;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-sampling "C:/Users/sakib/llama.cpp/build-android/bin/test-sampling")
set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;143;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grammar-parser "C:/Users/sakib/llama.cpp/build-android/bin/test-grammar-parser")
set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;144;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grammar-integration "C:/Users/sakib/llama.cpp/build-android/bin/test-grammar-integration")
set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;145;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-llama-grammar "C:/Users/sakib/llama.cpp/build-android/bin/test-llama-grammar")
set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;146;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat "C:/Users/sakib/llama.cpp/build-android/bin/test-chat")
set_tests_properties(test-chat PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;147;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-json-schema-to-grammar "C:/Users/sakib/llama.cpp/build-android/bin/test-json-schema-to-grammar")
set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "C:/Users/sakib/llama.cpp" _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;150;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-1-llama-spm "C:/Users/sakib/llama.cpp/build-android/bin/test-tokenizer-1-spm" "C:/Users/sakib/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;36;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;176;llama_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat-parser "C:/Users/sakib/llama.cpp/build-android/bin/test-chat-parser")
set_tests_properties(test-chat-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;182;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat-template "C:/Users/sakib/llama.cpp/build-android/bin/test-chat-template")
set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;183;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-json-partial "C:/Users/sakib/llama.cpp/build-android/bin/test-json-partial")
set_tests_properties(test-json-partial PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;184;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-log "C:/Users/sakib/llama.cpp/build-android/bin/test-log")
set_tests_properties(test-log PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;185;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-regex-partial "C:/Users/sakib/llama.cpp/build-android/bin/test-regex-partial")
set_tests_properties(test-regex-partial PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;186;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-arg-parser "C:/Users/sakib/llama.cpp/build-android/bin/test-arg-parser")
set_tests_properties(test-arg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;190;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-gguf "C:/Users/sakib/llama.cpp/build-android/bin/test-gguf")
set_tests_properties(test-gguf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;194;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-backend-ops "C:/Users/sakib/llama.cpp/build-android/bin/test-backend-ops")
set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;195;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-model-load-cancel "C:/Users/sakib/llama.cpp/build-android/bin/test-model-load-cancel")
set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;197;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-autorelease "C:/Users/sakib/llama.cpp/build-android/bin/test-autorelease")
set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;198;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-barrier "C:/Users/sakib/llama.cpp/build-android/bin/test-barrier")
set_tests_properties(test-barrier PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;202;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-quantize-fns "C:/Users/sakib/llama.cpp/build-android/bin/test-quantize-fns")
set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;203;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-quantize-perf "C:/Users/sakib/llama.cpp/build-android/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;204;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-rope "C:/Users/sakib/llama.cpp/build-android/bin/test-rope")
set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;205;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-mtmd-c-api "C:/Users/sakib/llama.cpp/build-android/bin/test-mtmd-c-api")
set_tests_properties(test-mtmd-c-api PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;102;add_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;210;llama_build_and_test;C:/Users/sakib/llama.cpp/tests/CMakeLists.txt;0;")
